name: 📚 Documentation report
description: Report problems with the docs. Request tutorials.
title: "[DOCS]: "
labels: [documentation]

body:
  - type: markdown
    attributes:
      value: |
        Hi there! Thank you for using typhoidsim. 
        ___

  - type: textarea
    id: what-happened
    attributes:
      label: Is there something wrong with the documentation? Is there any topic you'd like to have a tutorial about?
      placeholder: Tell us what you saw.
    validations:
      required: true
